bcgov/workbc-main

src/web/sites/default/settings.local.php
=> Disable twig caching in dev

src/composer.json, src/composer.lock, src/config/sync/editor.editor.basic_html.yml, src/config/sync/editor.editor.full_html.yml, src/config/sync/openid_connect.settings.yml, src/config/sync/views.view.search_career_profiles.yml, src/config/sync/views.view.search_site_content.yml, src/patches/drupal/time_field/3269302-Deprecated_function_trim_coalescing.patch, src/web/sites/default/default.settings.php
This PR upgrades dependencies:
- Drupal goes to 9.4.4 
- Other dependencies are upgraded
- `config_filter` is kept at version `~1` (don't move to 2.x) because of inconsistency in config ignore results
- Config sync is upgraded accordingly
- `time_field` patch is added
=> [WR-389] Upgrade Drupal and config

src/config/sync/block.block.exposedformsearch_career_profilespage_1.yml, src/config/sync/block.block.exposedformsearch_site_contentpage_1.yml, src/config/sync/block.block.related_topics.yml, src/config/sync/block.block.switchuser.yml, src/config/sync/block.block.views_block__blog_block_1.yml, src/config/sync/block.block.views_block__news_block_1.yml, src/config/sync/block.block.views_block__news_block_2.yml, src/config/sync/block.block.views_block__news_block_3.yml, src/config/sync/block.block.views_block__page_title_hero_no_hero_block_2.yml, src/config/sync/block.block.views_block__success_stories_block_1.yml, src/config/sync/block.block.views_block__video_library_block_1.yml, src/config/sync/block.block.workbc_content.yml, src/config/sync/block.block.workbc_help.yml, src/config/sync/block.block.workbc_local_actions.yml, src/config/sync/block.block.workbc_local_tasks.yml, src/config/sync/block.block.workbc_messages.yml, src/config/sync/block.block.workbc_page_title.yml, src/config/sync/block.block.workbccareereventsblock.yml, src/config/sync/block.block.workbcexplorecareersblock.yml, src/web/themes/custom/workbc/templates/layout/page.html.twig, src/web/themes/custom/workbc/workbc.info.yml
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-663
=> WR-663 Related topic layout updates - 2

src/composer.json, src/composer.lock, src/config/sync/core.extension.yml, src/config/sync/simple_sitemap.bundle_settings.default.menu_link_content.main.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.bc_profile.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.blog.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.career_profile.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.career_profile_introductions.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.event.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.industry_profile.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.labour_market_monthly.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.news.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.page.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.publication.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.region_profile.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.success_story.yml, src/config/sync/simple_sitemap.bundle_settings.default.node.workbc_centre.yml, src/config/sync/simple_sitemap.custom_links.default.yml, src/config/sync/simple_sitemap.settings.yml, src/config/sync/simple_sitemap.sitemap.default.yml, src/config/sync/simple_sitemap.type.default_hreflang.yml, src/config/sync/simple_sitemap.type.index.yml
Added sitemap module and its related configurations to meet the acceptance criteria.
=> WR-675 Added sitemap module and its related configurations

src/config/sync/block.block.bettersocialsharingbuttons.yml, src/config/sync/block.block.breadcrumbs.yml, src/config/sync/block.block.related_topics.yml, src/config/sync/block.block.sidenavblock.yml, src/config/sync/block.block.views_block__career_profiles_block_1.yml, src/config/sync/block.block.views_block__news_block_1.yml, src/config/sync/block.block.views_block__news_block_3.yml, src/config/sync/block.block.views_block__success_stories_block_1.yml, src/config/sync/block.block.views_block__video_library_block_1.yml, src/config/sync/block.block.webform.yml, src/config/sync/block.block.workbccareereventsblock.yml, src/config/sync/block.block.workbcexplorecareersblock.yml, src/config/sync/block.block.workbcmenublock.yml, src/web/themes/custom/workbc/templates/content/node--career-profile--full.html.twig, src/web/themes/custom/workbc/templates/content/node--page--full.html.twig, src/web/themes/custom/workbc/templates/includes/breadcrumbs.html.twig, src/web/themes/custom/workbc/templates/layout/page--4xx.html.twig, src/web/themes/custom/workbc/templates/layout/page.html.twig
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-747
https://hive.aved.gov.bc.ca/jira/browse/WR-748
=> WR-747: Theme updates fixes

src/config/sync/core.entity_form_display.node.page.default.yml, src/config/sync/paragraphs.paragraphs_type.action_card_full_width.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_1_2.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_1_3.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_1_4.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_explore_careers.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_full_width.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_icon.yml, src/config/sync/paragraphs.paragraphs_type.action_cards_publication.yml, src/config/sync/paragraphs.paragraphs_type.content_text.yml
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-785
=> WR-785: paragraph label UI updates

src/config/sync/block.block.bettersocialsharingbuttons.yml, src/config/sync/block.block.breadcrumbs.yml, src/config/sync/pathauto.pattern.labour_market_monthly.yml, src/web/themes/custom/workbc/templates/content/node--labour-market-monthly.html.twig
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-741
=> WR-741: Labour market base configs

Dockerfile, terraform/dev/ecs.tf
yarn command is required in https://github.com/bcgov/workbc-main/blob/master/src/scripts/sync.sh.
=> WR-832: install yarn in the drupal container

src/web/themes/custom/workbc/css/print.css, src/web/themes/custom/workbc/workbc.libraries.yml
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-648
=> WR-648 print styles

src/web/modules/custom/workbc_jobboard/README.txt, src/web/modules/custom/workbc_jobboard/src/Controller/apiServices.php, src/web/modules/custom/workbc_jobboard/templates/node-page-jobboard-account.html.twig, src/web/modules/custom/workbc_jobboard/templates/node-page-jobboard-findjobs.html.twig, src/web/modules/custom/workbc_jobboard/workbc_jobboard.module, src/web/sites/default/settings.aws.php, src/web/sites/default/settings.local.php
- Rename the frontend and backend job config vars
- Read the frontend config from an env var on AWS
=> Job Board configuration updates

src/config/sync/views.view.event_calendar_listview.yml, src/web/modules/custom/calendar_listview/templates/fields/views-view-fields-calendar-block-1.html.twig, src/web/modules/custom/workbc_jobboard/js/workbc_jobboard.js
In the list view, the start date of all events is showing today's date. 
This PR fixes that issue.
=> Fixes/wr 378  fixes start date field rename issue

src/config/sync/filter.format.full_html.yml, src/web/modules/custom/workbc_jobboard/templates/search-recent-jobs-block.html.twig
Ticket: 
https://hive.aved.gov.bc.ca/jira/browse/WR-1137
=> WR-1137: CKeditor updates and bug fixes

src/composer.json, src/composer.lock, src/config/sync/core.extension.yml, src/config/sync/editor.editor.basic_html.yml, src/config/sync/editor.editor.full_html.yml, src/config/sync/filter.format.basic_html.yml, src/config/sync/filter.format.full_html.yml, src/config/sync/image.style.linkit_result_thumbnail.yml, src/config/sync/linkit.linkit_profile.default.yml
Tickets:
https://hive.aved.gov.bc.ca/jira/browse/WR-764
@infojunkie the current version 6 of Linkit is in beta 3. It works as expected though.
=> WR-764: linkit additions and configs

src/config/sync/core.entity_view_display.node.blog.teaser.yml, src/config/sync/image.style.1_2_component.yml, src/config/sync/image.style.1_3_component.yml, src/config/sync/image.style.1_4_component.yml, src/config/sync/image.style.article_wide.yml, src/config/sync/image.style.explore_component.yml, src/config/sync/image.style.feature_component.yml, src/config/sync/image.style.full_width_component.yml, src/config/sync/image.style.hero_image.yml, src/config/sync/image.style.in_content_component.yml
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-1321
=> WR-1321: Image Styles Updates

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCUnemploymentRateBC.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCUnemploymentRateChart.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionUnemploymentRateBC.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionUnemploymentRateChart.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionUnemploymentRateRegion.php
Tickets: https://hive.aved.gov.bc.ca/jira/browse/WR-1401
=> WR-1401: Profile Label Updates

src/config/sync/core.entity_view_display.node.career_profile.full.yml, src/config/sync/core.entity_view_display.node.labour_market_monthly.full.yml, src/config/sync/core.entity_view_display.node.page.calendar.yml, src/config/sync/core.entity_view_display.node.workbc_centre.default.yml
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-1321
=> WR-1321: added missing image styles to hero

src/config/sync/block.block.webform_3.yml, src/config/sync/webform.webform.contact.yml
This PR disables the Contact Us webform as per WR-1574.
=> [WR-1574] Disable Contact Us webform

src/web/themes/custom/workbc/templates/layout/html.html.twig
Tickets: 
https://hive.aved.gov.bc.ca/jira/browse/WR-1583
=> WR-1583: Skip link

src/web/modules/custom/workbc_custom/workbc_custom.module
Fixed some clumsy code from WR-1322
=> WR-1560 fix breadcrumb error when editting an archived news article.

src/web/themes/custom/workbc/templates/content/node--career-profile--full.html.twig
There was already code in place to provide the "Show Less" button and functionality, just needed to provide labels for the two buttons for the code to behave as desired.
=> WR-1335 skills show less

src/web/modules/custom/workbc_custom/workbc_custom.module
Form alter to set checkbox default setting when deleting individual media items.
=> WR-1686 update form alter to default to TRUE for deleting individual media items

src/web/sites/default/settings.php
Update job board commit hash in `settings.php`
=> [WR-1386] update job board commit hash

src/composer.json
=> [WBCAMS-224] Fix better_social_sharing_buttons to 4.0.5

src/config/sync/core.entity_view_display.node.industry_profile.default.yml
=> WBCAMS-214 employment sub header missing

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentByAgeSexTable.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentIndustriesTable.php
Missed a couple tables that needed data columns right aligned.
=> WR-1738 update tables to right align data columns

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentIndustriesTable.php
=> WR-1628 add + for positive percentages

src/web/themes/custom/workbc/js/related-topics-carousel.js
Further changes as requested by Sai
=> [WR-1070] fix mobile tile display - version 2

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCEmployment.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCJobOpenings.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCPopulation.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCUnemploymentRate.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileJobOpenings.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmployment.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmploymentGrowth.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryJobOpenings.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionEmployment.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionJobOpenings.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionPopulation.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionUnemploymentRate.php
=> WR-1570 update dashboard labels to display year on second line

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileSkills.php
=> WR-1457 update Skills sort order

src/config/sync/webform.webform.workbc_order_form.yml, src/web/themes/custom/workbc/templates/form/webform--workbc-order-form.html.twig
=> WR-841 - WorkBC Order Form - Microcopy is misplaced

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/RegionProfile/RegionUnemploymentRate.php
I also did a quick check to see if any other Extra Fields returned "not available" or similar and didn't see any others.
=> WR-1613 update so field returns  "N/A" if null value is provided by SSoT

src/config/sync/editor.editor.full_html.yml, src/config/sync/filter.format.full_html.yml, src/web/modules/custom/workbc_custom/src/Plugin/Filter/FilterAllowAll.php
=> WR-1002 - ckeditor 5 filtering fix

src/web/modules/custom/workbc_custom/workbc_custom.module
=> re-format search results.

src/config/sync/core.extension.yml, src/web/modules/custom/workbc_custom/workbc_custom.module, src/web/themes/custom/workbc/js/mobile-chosen.js
enables Mobile Detect module, resolves 'illegal choice' & '0 selected' issues
=>  WR-1716-form-issues

src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
=> [WR-1737] update chart font sizes

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/BCProfile/BCFTPTEmploymentTable.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileSalaryInfoHourly.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryAverageWage.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryAverageWageBC.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmploymentTypesBC.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmploymentTypesCAN.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmploymentTypesIndustry.php
These updates resolve the L3 issues.  Deployment instructions and text files will be provided for the L2 pages with this issue
=> WR 1782 no headers identified

src/web/themes/custom/workbc/templates/content/node--industry-profile--full.html.twig
=> WbBCAMS-333 hourly earnings introduction text affects two locations

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryBCAverageChart.php, src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/IndustryProfile/IndustryEmploymentBySex.php, src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
=> WR-1799 pie chart updates

src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module, src/web/themes/custom/workbc/js/google-charts-redraw.js
Desktop
iPhone 14
Sansung Galaxy
=> WR-1799 chart legend caching

src/web/sites/default/settings.php
Trying again ... based on the `ams` branch instead of `master`
=> Update JB commit hash 0e5186c

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileJobOpeningsComposition.php
=> NOC-111 job composition chart data fix

src/config/sync/views.view.high_opportunity_occupations.yml
=> WBCAMS-343 bc profile  lms  employment by region table styling

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileEducationPrograms.php
=> NOC-340 education programs

src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/CareerProfile/CareerProfileIndustryHighlightsJobOpeningsByIndustry.php
=> NOC-363 career profiles   job openings by industry   do not display 0

src/config/sync/views.view.content.yml, src/config/sync/views.view.moderated_content.yml
I also updated the Moderated Content view to show Revision author.
Content view
Moderated content view
=> WBCAMS-544 author being displayed as anonymous

src/config/sync/field.field.node.bc_profile.field_tags.yml, src/config/sync/field.field.node.career_profile.field_tags.yml, src/config/sync/field.field.node.industry_profile.field_tags.yml, src/config/sync/field.field.node.labour_market_monthly.field_tags.yml, src/config/sync/field.field.node.region_profile.field_tags.yml, src/config/sync/field.field.node.workbc_centre.field_tags.yml
enable auto create tags for BC, Region, Career, Industry profiles, Labour Market Month and WorkBC Center metatag keyword fields
=> WBCAMS-557 metatag keywords

src/composer.json, src/composer.lock
upgrade modules that have had new releases since the previous updates
=> WBCAMS-688 module upgrades

src/config/sync/core.entity_view_display.node.page.default.yml
=> [WBCAMS-728] remove author and date info from search results 

src/config/sync/views.view.event_calendar.yml, src/web/modules/custom/calendar_listview/js/cv-custom.js
=> [WBCAMS-1031] calendar settings and bug fix

src/web/themes/custom/workbc/workbc.info.yml
remove counting at footer of page
=> wbcams-1212
